### ISSUE TITLE
Lack of OE license should fail cleanly 

### ISSUE THREAD

**Issue by hmacdope** [choderalab/asapdiscovery#149]
Some of the scripts have OpenEye dependencies, meaning they will hang if the `OE` license is not found or valid. 

We should have a clean fail on import to make sure this doesn't confuse peeople. 

The following snippet from @apayne97 should do the trick.

```python
oechem.OEChemIsLicensed("python")
```

could be turned to 

```python
if not oechem.OEChemIsLicensed("python"):
    raise RunTimeError("OpenEye license required")
```

We could have this run at module import to avoid having to put it in every script, but this would preclude non-openeye dependent scripts from running cleanly. 

Feedback welcome.

**Comment by apayne97** [comment]
@ijpulidos How does openff toolkit handle this? for those of use actually using the code right now this doesn't really matter since we all have the license. But it would be nice to future-proof this a bit. I don't think we can reasonably re-implement everything here without OpenEye so I'm fine with requiring an OpenEye license to run all the scripts for now

**Comment by apayne97** [comment]
Maybe we can programmatically add to all modules that have the `from openeye import` text?

**Comment by ijpulidos** [comment]
@apayne97 As far as I can tell, the openff-toolkit just falls back to using RDKit when it cannot find OpenEye.

@hmacdope Yes, we have the same problem with some scripts/entry-points for `perses`. I don't know if we have a clean way to deal with that other than what you mentioned. I guess that would be the best solution for now until we can come up with a better one. 

In my opinion this should be solved from the OpenEye side of things (by just raising an error instead of returning `False`). Maybe we could try raising the issue with them?
