### ISSUE TITLE
Not providing backticks around regex will fail on run_docking_oe.py, should fail more cleanly. 

### ISSUE THREAD

**Issue by hmacdope** [choderalab/asapdiscovery#206]
We should check that inputs into  -r argument of `run_docking_oe` are valid glob that will actually return something , and document/remove  the need for quotation marks when running the code.

**Comment by kaminow** [comment]
I don't think we can get rid of the need for the single ticks around the expression, since that's just the OS expanding wildcards. I can add something to the help text for the arg though to make that more clear. I think the files existing is checked in the `load_dus` method using your `check_filelist_has_elements` function, but are you seeing something not covered by that?

**Comment by hmacdope** [comment]
I keep tripping `    assert len(du_dict.keys()) > 0` on L 354 so perhaps filelist / glob checking is not working as I intended.

**Comment by kaminow** [comment]
@hmacdope are the filenames you're using formatted in the COVID Moonshot format? if not, I think the issue might be this part in `load_dus`: https://github.com/choderalab/asapdiscovery/blob/d8388c1ff7ac4257ad26e765673c393f0bd57f22/asapdiscovery-docking/asapdiscovery/docking/scripts/run_docking_oe.py#L100-L103
I can modify this function similarly to what we did #198, rather than trying to do the regex parsing within the function

**Comment by hmacdope** [comment]
I think that would be a good quality of life fix for sure. For the meantime, it seems to work fine using backticks, so perhaps action items. 

1. Add example script call in docs
2. Try and move hardcoded regexes as you did on last PR. 

Sound reasonable?

**Comment by kaminow** [comment]
@hmacdope I realized I'm being stupid, and we can just change the receptor CLI arg to accept multiple files. working on that and the regex change in #216

**Comment by hmacdope** [comment]
Brilliant, thanks. I'll review ASAP.
