### ISSUE TITLE
Use docking object instead of tuple of args in run_docking_oe

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#236]
I think we might have brought this up before but we're currently doing a thing where we pass in a series of arguments as a tuple to the `mp_func`, which then passes some of those arguments to the `run_docking_oe` func.

I'm wondering if using a more OOP approach would save the headache of having to always track which order the objects are in and using *args and **kwargs and so on.

Instead, having a object we pass to run_docking_oe might be able to keep track of these things for us?

thoughts?

**Comment by apayne97** [comment]
Potentially even better would be to mimic OpenEye and just have a docking object that contains different options for docking, initialization, etc and then we just run `ASAPDiscoveryDesignUnit.dock()`

**Comment by hmacdope** [comment]
Yeah this is very possibe / likely helpful. You could use a Pydantic `schema` or `namedtuple` if its doesn't need a lot of logic. If we need more we can make it a class and give it more logic. 

Speaking of `mp_func` we should rename them to something more descriptive so that they can be imported from the scripts (as is done in #246). Or we could even consider moving the respective functions to be library code.

**Comment by hmacdope** [comment]
Outdated now
