### ISSUE TITLE
add check during setup that all ligands are unique, i.e. make sure there are no duplicates in the series

### ISSUE THREAD

**Issue by dotsdl** [choderalab/asapdiscovery#469]

**Comment by dotsdl** [comment]
@JenkeScheen how unique is unique here? Can you define for me what level of unique you need in this context?

**Comment by JenkeScheen** [comment]
Good point. This is about molecular structure, I noticed that when we include two ligands that have the same structure (so beside atoms, also same binding pose), during analysis MLE breaks down. This is because if for a given edge `DDG == 0`, there ends up being a division by 0 in the MLE algorithm, resulting in an `np.inf` in a matrix, and then the whole thing breaking down. 

The easiest way to prevent this issue from happening is to catch it in the `asap-alchemy plan` phase, e.g. throwing an exception telling the user to remove duplicate ligands? There's quite a few ways to catch this, might be good to check for both SMILES match (or something more robust?) AND that `RMSD == 0` (just so we're not excluding enantiomers).

**Comment by dotsdl** [comment]
I've put together a possible solution in #76. Because the ligands are `gufe.SmallMoleculeComponent`s, they are hashable objects. Their hash is represented by their `.key` property, which is calculated from [their dict representation](https://github.com/OpenFreeEnergy/gufe/blob/441b70a6f716038dfa6c139c89c2ce2ebff6db14/gufe/components/smallmoleculecomponent.py#L196).

If that representation sufficiently matches what you mean by unique here (without being too strict for what you mean), then we should be good! I think based on what you described it is what we want here.
