### ISSUE TITLE
Save metadata alongside DU cache

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#574]
Related to #571 

When we cache DUs, it would be nice if we could store some metadata about what has been prepped alongside them. I had previously done this using the `modeler.schema.PreppedTargets.to_json` method using the Pydantic ability to convert schema objects to json.

**Comment by kaminow** [comment]
I feel like this might end up getting messy if we have to start tracking additional files with each `.oedu` file. my vote would probably be for forcing people to use the schema and serialize to JSON if they want to keep the metadata, especially since @hmacdope added the ability to cache both in the same function call

**Comment by hmacdope** [comment]
As @kaminow says, the best way to have the metadata attached is to save it in  the JSON's itself.  If we want to load oedus I think a name based match is simplest, but if it is not meeting needs can reassess

**Comment by hmacdope** [comment]
Closing for now as we will just prefer .jsons as of #608
