### ISSUE TITLE
Enable docking to *all* provided structures without needing to know how many there are

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#592]
i.e. right now this is required to be a positive integer:

https://github.com/choderalab/asapdiscovery/blob/3839851460c93f0555f3044fdfd0c92f27b94a12/asapdiscovery-docking/asapdiscovery/docking/workflows/large_scale_docking.py#L69-L70

whereas before you could pass `-1` and it would just dock to everything
https://github.com/choderalab/asapdiscovery/blob/3839851460c93f0555f3044fdfd0c92f27b94a12/asapdiscovery-docking/asapdiscovery/docking/scripts/run_docking_oe.py#L237-L242

**Comment by hmacdope** [comment]
Its unlikely that we want to use all structures in a project support sense, but does the cross-docking workflow now cover this case? 

Otherwise shouldn't be too hard to add anyway. Rather than a change to `top_n` it should be a configurable switch to the `PairwiseSelector` much as you have in the crossdocking wf now.

**Comment by apayne97** [comment]
Yeah I think this is resolved by having a cross_docking_workflow!
