### ISSUE TITLE
Use logger instead of print statements in POSITDocker

### ISSUE THREAD

**Issue by apayne97** [choderalab/asapdiscovery#600]
https://github.com/choderalab/asapdiscovery/blob/f0292fd130312179e31d838774e3dc6c88c9239d/asapdiscovery-docking/asapdiscovery/docking/docking_v2.py#L386-L399

**Comment by hmacdope** [comment]
Yes agree we need to do a whole rework of how logging works in the new workflows. Basically we need to stop 
`self.logger()` calls because then you need a logging object, instead you need a `logging.info` macro level call, but this wasn't being picked up by `FileLogger`. I will make a seperate issue.

**Comment by apayne97** [comment]
My concern with that is that I think we lose the parent / child logging functionality because everything will get logged to the top level, which can make a mess

**Comment by hmacdope** [comment]
This is fixed now
