### ISSUE TITLE
Move v2 imports in `asapdiscovery-ml` to root level and rename to not have v2 in module and class names

### ISSUE THREAD

**Issue by hmacdope** [choderalab/asapdiscovery#781]
As above

**Comment by kaminow** [comment]
@hmacdope is the plan to also get rid of old stuff here or should that be a separate PR?

**Comment by hmacdope** [comment]
Whatever is easiest for you, if ripping out is easy then go for it.

**Comment by kaminow** [comment]
I think for the most part it'll be easy, with the main exception of `inference.py`, which will require some code rewriting. I'm happy to do it, and it'll need to be done at some point anyway, just wanted to check if you think it's fine to have everything together or if we should separate into different PRs for posterity reasons

**Comment by hmacdope** [comment]
Its honestly fine either way, whatever works best for you.

**Comment by kaminow** [comment]
heard, I'll just do it all in the same PR then

**Comment by kaminow** [comment]
@hmacdope I'm in the process of reworking the `Inference` classes to use the new `mtenn.*ModelConfig` classes, but I'm realizing that the old config files in the `asap_models.yaml` file are no longer compatible. I'll need to generate new config files for these models, which should be fairly trivial, but I'm not sure whether it makes more sense to overwrite the existing config files and just change the hash in `asap_models.yaml`, or if I should make new model config files (eg `asapdiscovery-GAT-config-2023.04.12_v2.json` or something). It feels somewhat antithetical to the point of this refactor to introduce new stuff with `v2` in the name, but I think in this case it might make sense so that we can retain the old files in case anyone wants to use `asapdiscovery-ml v0.2.0` for whatever reason. but let me know what you think

**Comment by kaminow** [comment]
alternatively, another option is to just clean the file out and train all new models with the new pipeline and put those in instead

**Comment by hmacdope** [comment]
I am happy to clean out the file if that is easier, might be nice to start from a clean slate.

**Comment by kaminow** [comment]
sounds good, I'll go that route then

**Comment by hmacdope** [comment]
Actually @kaminow would you be able to provide updated config files in the meantime, before re-worked models are deployed? 

Unless re-deploying is low effort, I think we might need a stopgap. I guess it kind of depends on how long for re-trained models.

**Comment by hmacdope** [comment]
Sorry for the flip-flop

**Comment by kaminow** [comment]
I think redeploying will actually probably be less effort overall than rewriting the config files, and training is relatively short (max of ~half a day I think). I can definitely still do the updated configs if you think it's necessary, but I don't think training new models will hold us up too much and nothing will be broken until we merge #810 anyway

**Comment by hmacdope** [comment]
Ah okay, that is my misunderstanding, I didn't realise breaking change was #810. You are right, probably no need for updated configs, lets start with a fresh slate for #810.

**Comment by kaminow** [comment]
all good. I did the refresh and the clean new `asap_models.yaml` file is in the most recent version of #810
